title: Aprameya Girish Hebbar
description: Mathematical writing, research, and ideas
author: Aprameya Girish Hebbar
theme: minima
markdown: kramdown
collections:
  expository_posts:
    output: true
    permalink: /expository/:name/