title: Name
description: Mathematical writing, research, and ideas
author: Name
theme: minima
markdown: kramdown

kramdown:
  parse_block_html: true

collections:
  expository_posts:
    output: true
    permalink: /expository/:name/

  stuff:
    output: true
    permalink: /stuff/:name/

